### ISSUE TITLE
Disable internet access for the tests

### ISSUE THREAD

**Issue by lukemarsden** [dotmesh-io/dotmesh#371]
The test dinds shouldn't need to pull images from the internet, if they do then things got out of date.

Disable internet access in the test dinds to force us to keep our caches up to date.

**Comment by alaric-dotmesh** [comment]
It's a pain when we want to `apt-get install` some tool in a dind container for debuggering, though...

Suggestion:

1. Fix the current problem with the docker network being `192.168.*.*` that means it has problems doing NAT when your home network is `192.168.something.something`, by using `192.168.195.*` instead of the whole /16
2. Extract the code that sets up NAT (spelt "masquerading" in ipchains land) from the test dind setup so there's no NAT by default.
3. Put it in `citools/scripts/enable_dind_nat.sh` script we can run when we want to hack with stuff.
4. Write a `citools.scripts/disable_dind_nat.sh` script to reverse it.
