### ISSUE TITLE
Ensure Kubernetes does not kill zpools in PVs

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#463]
This is part of epic #385 

Acceptance criteria: In all of the following cases, all your dots are still accessible.

- [ ] PV Per Node mode GKE clusters can be upgraded (in the sense of upgrading k8s).
- [ ] PV Per Node mode clusters can have a node deleted and a new one created, and the old PVC gets reused.
- [x] PV Per Node mode clusters can have Dotmesh upgraded on them and keep working.

See the document on [Problems with ZFS in a k8s PV](https://docs.google.com/document/d/1uuaE5WZux8XAJ5QP67peY7SXoIAaNG2OaDorhd5vjCw/edit#heading=h.tgnv0snuiu07).

How do we fix this? PVC-per-node mode clusters will slowly accumulate broken zpools, and need manual fscks of the ext4 filesystems in the PVCs, until we can make sure that the zpools get shut down cleanly in all cases.

**Comment by prisamuel** [comment]
Hrm.. this is going to be an ongoing issue and a blocker for continuous deployment into the production cluster. Upgrading the backup cluster (in PVPerNodeMode) with the latest images, spins on pod creation. 

![jun-22-2018 10-51-16](https://user-images.githubusercontent.com/151395/41770480-3fa962ae-760a-11e8-9e04-e699a8a8487c.gif)

**Comment by prisamuel** [comment]
- [x]  PV Per Node mode clusters can have Dotmesh upgraded on them and keep working.

On a dotmesh server upgrade, the following events happen. 
- The sentinels just hang around attached to the PVC's. The sentinels are just instances of docker busybox and they are not versioned with the dotmesh server.
- The running version of the dotmesh operator is destroyed and a new instance is deployed.
- The new dotmesh operator does a check of the running versions of dotmesh-server pods and marks any old versions as stale and deletes them. 
- The operator then creates a new dotmesh-server pods on nodes, reusing PVC's that are currently on those nodes.

In cases which require node restarts (below) - such as a k8s upgrade and nodes being deleted and new ones being created. The order in which k8s deletes pods is non-deterministic, so the sentinel may die before the dotmesh-server and never have a chance to run `shutdown.sh`

- [ ] PV Per Node mode GKE clusters can be upgraded (in the sense of upgrading k8s).

This didn't quite work as the etcd cluster never came back up after an upgrade from 1.10.0 to 1.10.5. Also because k8s decided to kill the sentinels before the dotmeshes, the zpool came back up in a sorry state. In any case, the PVC's exist and manual intervention is required for use case.

- [ ] PV Per Node mode clusters can have a node deleted and a new one created, and the old PVC gets reused.

Again, k8s decided to kill the sentinels before dotmeshes. The old PVC exists and this needed to be fsck-ed before it could be reused.
