### ISSUE TITLE
Selective (faster!) builds

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#467]
Building dotmesh takes a while, which is annoying when you've just changed one little thing.

We have a bunch of discrete steps - operator, dind-flexvolume, dynamic provisioner, server, flexvolume driver, dm client - that can be built separately; we do some go compile caching, but it still takes a long time to set up the docker containers and build things in them.

So, a time saving may be had by having each build step compute a checksum of the source directories that go into that build (including `vendor`!), and comparing them to a checksum stored in a file from the last build, and skipping the build if there's no change.

Prototype it, and measure the difference. If it doesn't help enough to make it worth the complexity in the build system, abandon that commit.

**Comment by lukemarsden** [comment]
Or use https://bazel.build/

**Comment by Godley** [comment]
Measured using `time` before starting this issue:
```
real	1m50.339s
user	0m42.744s
sys	0m12.796s
```
(https://stackoverflow.com/questions/556405/what-do-real-user-and-sys-mean-in-the-output-of-time1/556411#556411)
I'm planning to look into using bazel first so that we don't roll our own unnecessarily

**Comment by Godley** [comment]
Operator fails to build at the moment, but using bazel having built the client/server/provisioner/volume driver before...
```
real    0m5.655s
user    0m0.148s
sys     0m0.208s
```

**Comment by Godley** [comment]
Having built everything once (and with no failures) already:
```
real    0m2.820s
user    0m0.138s
sys     0m0.191s
``` 
will clear the caches and see how long it takes to build everything...

**Comment by Godley** [comment]
Stuff to address:
1. Tagging docker images based on versioner output
2. Changing registry depending whether this is in ci, locally or being released
3. Cross compiling for macos: https://github.com/bazelbuild/rules_go/issues/1597
4. Docker image building for the server + dind stuff

**Comment by Godley** [comment]
Final timing:
```
real	0m58.691s
user	0m34.176s
sys	0m1.996s
```

And probably most of that is for the server, which is the only part which uses docker for building (just the base layer). If it gets slower again we should look into 
a) changing the process in `cmd/dotmesh-server/BUILD.bazel` to create a `container_layer` containing `require_zfs.sh`, which is included in `container_image`
b) figuring out how we can get bazel to pull down the `docker` binary and include it in a similar way.

The first is probably easy enough (I just haven't done it because we still need docker to do the second one), second I couldn't figure out how to do.
