### ISSUE TITLE
Split statemachines.go by state

### ISSUE THREAD

**Issue by alaric-dotmesh** [dotmesh-io/dotmesh#497]
As a dotmesh developer, I want to not have a 3,972 line file in my project, so that I can actually do my job.

Therefore, I'd like to split statemachines.go into separate files - one per state, plus one for the shared core - with suitable names, so it's clear where I need to look for things.

**Comment by Godley** [comment]
Pretty much done here, I've split out all of the states into their own files (ending in `state` so it's clear). I've also pulled out as much of the "generic" functions into well named files since after that it was still a pretty huge file. Will probably raise an issue with some more work I think could be done on this.
