### ISSUE TITLE
[1d?] Big pushes break after 10G - bad!

### ISSUE THREAD

**Issue by alice-sowerby** [dotmesh-io/dotmesh#655]
- Kai started testing this and it broke after 10G

See https://github.com/dotmesh-io/dotmesh/issues/603 for notes on stress-testing Dotmesh in general - which should test this kind of case.

**Comment by alaric-dotmesh** [comment]
We now have some stress tests that do 20G push/pull/peer transfers... and they seem to work fine.

So whatever's happening here must be a problem with the deployment/configuration of dotmesh in dotscience, rather than DM itself. Something to do with the networking setup, I guess? Issue https://github.com/dotmesh-io/gateway/issues/144 created to investigate.
